# Generated by Django 4.0.3 on 2022-07-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping_Address',
            new_name='ShippingAddress',
        ),
    ]
