# Generated by Django 4.0.3 on 2022-08-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='date_order',
        ),
    ]
